---
title: "Background"
author: "Sölvi Rögnvaldsson"
date: "2023-05-15"
output: html_document
---

Seasonal variation has affected human societies throughout history, shaping various aspects of life including agriculture, migration patterns and culture. This influence is observed, among others, in the occurrences of diseases such as viral and bacterial infections, cardiovascular disease and mental disorders. While there are a multitude of factors influencing the timing of disease diagnoses, environmental and behavioural, the genetic role has not been explored to the best of our knowledge. The aim of this project is to relate genetic variation to seasonal disease risk.   

This Shiny dashboard presents two products from the Master's thesis "Assessing the genetic role in seasonal disease risk in the Finnish population" by Sölvi Rögnvaldsson. The first product is a seasonality model inferred for 1,759 clinical endpoints using longitudinal data from the FinRegistry project. The coresponding dashboard allows browsing the seasonality of different endpoints in an interactive way. The second product is a modeling framework which enables associating genetic variants to seasonal disease risk. The corresponding dashboard allows simulating from the proposed modeling framework to see how different parameters affect the generated data.

The code for the project is available at: [https://github.com/dsgelab/seasonality](https://github.com/dsgelab/seasonality).
